# Ruby はあなたの指定に合わせて 3.2.2
FROM ruby:3.2.2

# ロケール / タイムゾーン
ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo

# 必要パッケージ：ビルド系 & PostgreSQLクライアントヘッダ
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
      build-essential \
      libpq-dev \
      ca-certificates \
      curl \
      vim && \
    rm -rf /var/lib/apt/lists/*

# アプリディレクトリ
WORKDIR /app

# bundler 事前インストール（バージョン縛り不要ならこのまま）
#RUN gem install bundler

# 依存解決はキャッシュを効かせるために先に Gemfile だけコピー
#COPY Gemfile Gemfile.lock ./
#RUN bundle install

# ソースをコピー
COPY . .

# Rails の旧PID掃除用 entrypoint
#COPY docker/entrypoint.sh /usr/bin/
#RUN chmod +x /usr/bin/entrypoint.sh
#ENTRYPOINT ["entrypoint.sh"]

# ポート
EXPOSE 3000

# サーバ起動
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]